name: phone_number_metadata
description: phone metadata from lib phone number as dart consts
version: 5.0.0
homepage: https://github.com/cedvdb/dart_phone_metadata

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  path: ^1.8.0
  dart_countries: ^3.0.1

dev_dependencies:
  pedantic: ^1.10.0
